---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  template:
    spec:
      containers:
      - name: argocd-server
        volumeMounts:
          - mountPath: /mnt/secrets/tls
            name: tls
            readOnly: true
          - mountPath: /mnt/secrets/k8sbase
            name: argocdrepos
            readOnly: true
      volumes:
        - name: tls
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: tls
        - name: argocdrepos
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: k8s-base
