---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  oidc.config: |
    name: Azure
    issuer: $oidc.azure.issuer
    clientID: $oidc.azure.clientID
    clientSecret: $oidc.azure.clientSecret
    requestedIDTokenClaims:
        groups:
            essential: true
    requestedScopes:
        - openid
        - profile
        - email
  url: https://argocd.imjoseangel.eu
