---
apiVersion: v1
data:
  project: ZGVmYXVsdA==
  type: Z2l0
  url: aHR0cHM6Ly9naXRodWIuY29tL2ltam9zZWFuZ2VsL2dpdG9wcy1hcmdvLmdpdA==
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: k8s-base
type: Opaque
