---
namespace: argocd

bases:
  - base/namespace.yaml
  - base/secrets-store.yaml

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - resources/argocd.yaml
  - resources/ingress.yaml
  - config/argocd-repos.yaml
  - config/argocd-secret.yaml
  - config/argocd-ingress.yaml

patchesStrategicMerge:
  - patches/argocd-secrets-mounts.yaml
  - patches/argocd-cm.yaml
  - patches/argocd-rbac-cm.yaml
  - |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: argocd-secret
    $patch: delete
