---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - base/deployment.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
#  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/ha/install.yaml
