---
namespace: argocd

bases:
  - base/namespace.yaml
  - base/secrets-store.yaml

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/ha/install.yaml
  - resources/argocd.yaml
  - resources/ingress.yaml
  - resources/argocd-ingress.yaml

patchesStrategicMerge:
  - patches/argocd-secrets-mounts.yaml
