---
namespace: airflow

bases:
  - base/namespace.yaml

helmCharts:
  - name: airflow
    repo: https://airflow.apache.org
    version: 1.6.0
    releaseName: airflow
    namespace: airflow
    valuesFile: resources/values.yaml

# run with kubectl kustomize airflow --enable-helm | kubectl apply -f -
